import { mkdirSync, writeFileSync, chmodSync, existsSync, unlinkSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join } from "node:path";
import { repoAegisHome, appendAuditRecord } from "@de-otio/repo-aegis-core";
import { emitJson, emitText, emitError, type OutputOptions } from "../format.js";

// Hook scripts. This file is the SINGLE source of truth for the
// installed scripts; the standalone .sh.template files were removed
// to eliminate drift. Edit here, rebuild, run `install hooks` again
// to refresh installed copies.

const PRE_COMMIT_SCRIPT = `\
#!/usr/bin/env bash
# Generated by \`repo-aegis install hooks\`. Do not edit; overwritten on
# every \`install hooks\` run. Source of truth: packages/cli/src/commands/
# install-hooks.ts (PRE_COMMIT_SCRIPT).
#
# Fail-open if repo-aegis is not on PATH so the git workflow doesn't
# break for users who haven't yet installed the CLI globally.
set -euo pipefail

if ! command -v repo-aegis >/dev/null 2>&1; then
  exit 0
fi

# Never pass --verbose: hook output flows into the agent's tool result
# and must not echo literal markers.
exec repo-aegis check --staged
`;

const PRE_PUSH_SCRIPT = `\
#!/usr/bin/env bash
# Generated by \`repo-aegis install hooks\`. Source of truth:
# packages/cli/src/commands/install-hooks.ts (PRE_PUSH_SCRIPT).
#
# Reads stdin lines of \`<local-ref> <local-sha> <remote-ref> <remote-sha>\`
# and runs \`repo-aegis check --range\` per updated branch. New branches
# scan from the empty-tree sha so every commit reachable on the new
# branch is covered (not just the working tree). Branch deletions skip.
set -euo pipefail

if ! command -v repo-aegis >/dev/null 2>&1; then
  exit 0
fi

zero="0000000000000000000000000000000000000000"
empty_tree="4b825dc642cb6eb9a060e54bf8d69288fbee4904"

exit_rc=0
while read -r local_ref local_sha remote_ref remote_sha; do
  : "$local_ref" "$remote_ref"
  if [ "$local_sha" = "$zero" ]; then
    continue
  fi
  if [ "$remote_sha" = "$zero" ]; then
    range="\${empty_tree}..\${local_sha}"
  else
    range="\${remote_sha}..\${local_sha}"
  fi
  if ! repo-aegis check --range "$range"; then
    echo "repo-aegis: hits in range $range (ref: $local_ref)" >&2
    exit_rc=1
  fi
done

exit "$exit_rc"
`;

interface InstallHooksOptions extends OutputOptions {
  force?: boolean;
  cwd?: string;
  /**
   * When true, do the work but suppress all stdout/stderr emission
   * (no emitJson / emitText). emitError still fires on hard failure
   * (which calls process.exit). Used by `init` to call this command
   * inline without polluting init's own output stream.
   */
  silent?: boolean;
  /**
   * When true, reverse the install: unset core.hooksPath (idempotent;
   * a "not set" failure is silently ignored) and remove the
   * pre-commit / pre-push files under <repoAegisHome>/hooks if they
   * exist. The hooks directory itself is left in place because other
   * tooling may store files there.
   */
  uninstall?: boolean;
}

function git(cwd: string, args: string[]): { ok: boolean; stdout: string } {
  try {
    const stdout = execFileSync("git", args, {
      cwd,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    return { ok: true, stdout };
  } catch {
    return { ok: false, stdout: "" };
  }
}

interface UninstallHooksContext {
  cwd: string;
  hooksDir: string;
  preCommitPath: string;
  prePushPath: string;
  opts: InstallHooksOptions;
}

function uninstallHooks(ctx: UninstallHooksContext): void {
  const { cwd, hooksDir, preCommitPath, prePushPath, opts } = ctx;

  // Capture the pre-existing core.hooksPath so the report can describe
  // what was unset. Falls back to empty string when the key is unset.
  const before = git(cwd, ["config", "--get", "core.hooksPath"]);
  const previousHooksPath = before.ok ? before.stdout : "";

  // `git config --unset` exits 5 when the key is not set; treat that as
  // a no-op so the command is idempotent.
  let unsetPerformed = false;
  try {
    execFileSync("git", ["config", "--unset", "core.hooksPath"], {
      cwd,
      stdio: ["ignore", "ignore", "ignore"],
    });
    unsetPerformed = true;
  } catch {
    // Already unset (or git emitted an error we can safely swallow);
    // remain idempotent.
  }

  const removed: string[] = [];
  for (const p of [preCommitPath, prePushPath]) {
    if (existsSync(p)) {
      try {
        unlinkSync(p);
        removed.push(p);
      } catch (err) {
        emitError(
          {
            code: "FS_ERROR",
            error: `failed to remove ${p}: ${(err as Error).message}`,
          },
          opts,
        );
      }
    }
  }

  if (opts.silent) return;

  if (opts.json) {
    emitJson({
      action: "uninstall-hooks",
      hooksDir,
      removed,
      coreHooksPathUnset: unsetPerformed,
      previousCoreHooksPath: previousHooksPath || null,
    });
    return;
  }

  if (unsetPerformed) {
    emitText(
      previousHooksPath
        ? `unset core.hooksPath (was: ${previousHooksPath})`
        : "unset core.hooksPath",
    );
  } else {
    emitText("core.hooksPath was not set (nothing to unset)");
  }
  if (removed.length > 0) {
    for (const p of removed) emitText(`removed ${p}`);
  } else {
    emitText(`no hook scripts to remove under ${hooksDir}`);
  }
}

export function installHooks(opts: InstallHooksOptions): void {
  const cwd = opts.cwd ?? process.cwd();

  const inside = git(cwd, ["rev-parse", "--is-inside-work-tree"]);
  if (!inside.ok || inside.stdout !== "true") {
    emitError({ code: "NOT_GIT_REPO", error: "not inside a git repository" }, opts);
  }

  const hooksDir = join(repoAegisHome(), "hooks");
  const preCommitPath = join(hooksDir, "pre-commit");
  const prePushPath = join(hooksDir, "pre-push");

  if (opts.uninstall) {
    uninstallHooks({
      cwd,
      hooksDir,
      preCommitPath,
      prePushPath,
      opts,
    });
    return;
  }

  const existing = git(cwd, ["config", "--get", "core.hooksPath"]);
  const previousHooksPath = existing.ok ? existing.stdout : "";
  const conflict = previousHooksPath !== "" && previousHooksPath !== hooksDir;

  if (conflict && !opts.force) {
    emitError(
      {
        code: "HOOKS_PATH_CONFLICT",
        error: "core.hooksPath is already set to a different path",
        details:
          `current: ${previousHooksPath}\n` +
          `  target:  ${hooksDir}\n` +
          `  --force will OVERWRITE (destroy) the prior value "${previousHooksPath}"; ` +
          `if that path is still needed, save it before re-running with --force.`,
      },
      opts,
    );
  }

  try {
    mkdirSync(hooksDir, { recursive: true, mode: 0o700 });
    try {
      chmodSync(hooksDir, 0o700);
    } catch {
      /* platform-restricted */
    }

    writeFileSync(preCommitPath, PRE_COMMIT_SCRIPT, { mode: 0o755 });
    chmodSync(preCommitPath, 0o755);

    writeFileSync(prePushPath, PRE_PUSH_SCRIPT, { mode: 0o755 });
    chmodSync(prePushPath, 0o755);
  } catch (err) {
    emitError(
      { code: "FS_ERROR", error: `failed to write hook scripts: ${(err as Error).message}` },
      opts,
    );
  }

  try {
    execFileSync("git", ["config", "core.hooksPath", hooksDir], {
      cwd,
      stdio: ["ignore", "ignore", "ignore"],
    });
  } catch (err) {
    emitError(
      { code: "GIT_CONFIG_ERROR", error: `failed to set core.hooksPath: ${(err as Error).message}` },
      opts,
    );
  }

  // Audit (best-effort). Emit AFTER the git config is set so the
  // record reflects persisted state. `cwd` carries the targeted repo.
  try {
    appendAuditRecord({
      action: "install-hooks",
      cwd,
      repo: cwd,
      details: { hooksDir, overwritten: conflict, previousCoreHooksPath: previousHooksPath || null },
    });
  } catch {
    /* audit log must not break user-facing ops */
  }

  if (opts.silent) return;

  if (opts.json) {
    emitJson({
      action: "install-hooks",
      hooksDir,
      installed: ["pre-commit", "pre-push"],
      coreHooksPath: hooksDir,
      previousCoreHooksPath: previousHooksPath || null,
      overwritten: conflict,
    });
    return;
  }

  emitText(`installed hooks at ${hooksDir}`);
  emitText(`set core.hooksPath = ${hooksDir}`);
  if (conflict) {
    emitText(`  (previous value: ${previousHooksPath} — overwritten with --force)`);
  }
}
