// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Richard Myers and contributors.
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { appendAuditRecord } from "@de-otio/repo-aegis-core";
import { emitJson, emitText, emitError, type OutputOptions } from "../format.js";

/**
 * Which generated workflow(s) to emit.
 *
 * - `pr`     — the blocking gate: every PR, every push to a default branch,
 *              every tag, and the `public` event.
 * - `strict` — the scheduled conscience: runs with waivers and allow-comments
 *              ignored, so suppression creep is visible somewhere.
 *
 * They are separate files rather than two jobs in one because their
 * permissions differ (strict needs `issues: write`, which must never be
 * reachable from a PR-triggered job) and because an operator may reasonably
 * want one without the other.
 */
export type CiProfile = "pr" | "strict";

const PR_WORKFLOW_PATH = ".github/workflows/leak-scan.yml";
const STRICT_WORKFLOW_PATH = ".github/workflows/leak-scan-strict.yml";

// Action pins. Full 40-hex commit SHAs, not floating majors: this workflow is
// a security gate, and a gate that an upstream tag-move can rewrite is not a
// gate. Every entry below was verified to declare `runs.using: node24`.
//
// These do go stale. `install ci` also emits a Dependabot fragment (see
// `dependabotFragment` at the bottom of this file) so a consumer can have the
// pins maintained for them; the alternative — floating majors — trades a
// maintenance task for a supply-chain hole.
const PIN_CHECKOUT = "actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3";
// The trailing zizmor directive: its cache-poisoning audit fires on
// setup-node because that action CAN enable dependency caching — the
// generated workflows never pass `cache:`, so there is no cache to poison.
const PIN_SETUP_NODE =
  "actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0  # zizmor: ignore[cache-poisoning]";
const PIN_GITHUB_SCRIPT = "actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0";

/** Version of this CLI, embedded into the generated workflow's install step. */
function packageVersion(): string {
  try {
    const here = dirname(fileURLToPath(import.meta.url));
    const pkg = JSON.parse(readFileSync(join(here, "..", "..", "package.json"), "utf8")) as {
      version: string;
    };
    return pkg.version;
  } catch {
    // Should not happen in a published install; `latest` is the honest
    // fallback rather than a version string we cannot substantiate.
    return "latest";
  }
}

/**
 * The install step, shared by every generated job.
 *
 * Three things here are load-bearing and should not be "simplified" away:
 *
 *   - `working-directory: ${{ runner.temp }}` — npm reads `./.npmrc` from the
 *     current directory. Run from the checkout, a PR-supplied `.npmrc` can
 *     repoint the registry and substitute the package. Installing from
 *     outside the workspace removes the file from npm's search path.
 *   - `--ignore-scripts` — even with the right registry, a package's install
 *     scripts should not run in a job that may hold a registry secret.
 *   - `--registry=...` — belt to the working-directory braces: an explicit
 *     registry cannot be overridden by config discovered elsewhere.
 *
 * The version is pinned to the CLI that generated the file, not `latest`: a
 * compromised publish would otherwise reach every consumer's gate on their
 * next run.
 */
function installStep(indent: string): string {
  const v = packageVersion();
  return [
    `${indent}- name: Install repo-aegis`,
    `${indent}  # Installed from outside the checkout so a PR-supplied .npmrc`,
    `${indent}  # cannot repoint the registry, with scripts disabled and the`,
    `${indent}  # registry stated explicitly. See doc/github-action.md.`,
    `${indent}  working-directory: \${{ runner.temp }}`,
    `${indent}  env:`,
    `${indent}    REPO_AEGIS_VERSION: '${v}'`,
    // zizmor's adhoc-packages audit flags any install outside a lockfile.
    // Installing the scanner IS the step, so there is nothing to lock; the
    // supply-chain risk it is really pointing at is addressed by the pinned
    // version, --ignore-scripts, and the explicit registry above.
    `${indent}  run: | # zizmor: ignore[adhoc-packages]`,
    `${indent}    npm install -g --ignore-scripts --registry=https://registry.npmjs.org \\`,
    `${indent}      "@de-otio/repo-aegis@\${REPO_AEGIS_VERSION}"`,
  ].join("\n");
}

const PR_WORKFLOW_CONTENT = `\
# Generated by \`repo-aegis install ci\` (profile: pr).
#
# The blocking gate. Runs on every PR, every push to a default branch, every
# tag, and on the \`public\` event. Regenerate with \`repo-aegis install ci
# --profile pr --write --force\`; edit it and \`install ci --uninstall\` will
# refuse to delete it (it only removes files it recognises byte-for-byte).
#
# Three flags below are deliberate and worth understanding before you change
# them:
#
#   --no-hooks-check  Do NOT remove. It skips the git-hooks liveness check,
#                     which verifies repo-aegis's pre-commit/pre-push hooks are
#                     wired via core.hooksPath. A CI runner checks out a fresh
#                     clone with no hooks installed, so the check would fail on
#                     every run — a guaranteed false positive. Hook liveness is
#                     a developer-machine concern; \`repo-aegis doctor\` sweeps
#                     for it across your repos.
#
#   --require-deny-set  Fail if the computed deny set is empty. Without it, a
#                     registry that failed to load (a fork PR cannot read
#                     secrets; a renamed secret; a bad path) produces a scan
#                     that matches nothing and a green check indistinguishable
#                     from a real pass. A gate that silently no-ops is worse
#                     than no gate.
#
#   REPO_AEGIS_REDACT_ATTRIBUTION  Strips engagement ids from output. A job log
#                     on a public repo is world-readable, and an engagement id
#                     is usually the customer's name. Findings keep file, line,
#                     and counts, which is what makes them actionable.
name: leak-scan

on:
  pull_request:
  push:
    branches: [main, master]
    # A tag can introduce content no branch push ever carried, and the local
    # pre-push hook reads possibly-stale remote-tracking refs. Here the remote
    # state is authoritative.
    tags: ['**']
  # Fires when a repo flips private -> public: the one moment the threat model
  # changes wholesale. Everything previously safe-because-private is now not.
  public:

permissions:
  contents: read

concurrency:
  group: leak-scan-\${{ github.ref }}
  cancel-in-progress: \${{ github.event_name == 'pull_request' }}

jobs:
  leak-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    env:
      # CI knows this repo's visibility authoritatively; a fresh clone has no
      # cached value for the egress check to read. The variable is
      # one-directional by design — it can assert "public" (which turns
      # private-registry egress enforcement ON) and there is no counterpart
      # that asserts "private", because an env var that switches findings off
      # is a waiver nobody reviewed.
      REPO_AEGIS_ASSUME_PUBLIC: \${{ github.event.repository.private == false && '1' || '0' }}
      REPO_AEGIS_REDACT_ATTRIBUTION: '1'
    steps:
      - name: Checkout
        uses: ${PIN_CHECKOUT}
        with:
          fetch-depth: 0
          # The scan never pushes. Leaving the token in .git/config only
          # widens what a later step (or an uploaded artifact) could expose.
          persist-credentials: false
      - name: Set up Node.js
        uses: ${PIN_SETUP_NODE}
        with:
          node-version: '24'
${installStep("      ")}
      - name: Marker scan
        # One process for the whole repo, not one per file: audit's JSON
        # enumerates findings with file:line, so a non-zero exit already
        # identifies the offending file. --verbose is never passed here — a CI
        # log is no more private than a PR comment.
        #
        # The lockfile/egress check is ON (it was off in pre-0.8.0 templates):
        # a private-registry URL in a lockfile leaks an account id and breaks
        # \`npm ci\` for external clones, and REPO_AEGIS_ASSUME_PUBLIC above is
        # what lets it decide correctly on a fresh checkout.
        run: |
          repo-aegis audit --json \\
            --require-deny-set \\
            --no-history \\
            --no-fixture-check \\
            --no-remote-check \\
            --no-hooks-check

  # A new ref can carry content no branch push ever showed. \`check --push-ref\`
  # normally derives its range from remote-tracking refs, which a local hook
  # can never refresh; on a runner they are as fresh as the fetch, and a
  # missing tracking ref degrades to a full-history scan — an over-scan, never
  # an under-scan.
  new-ref-scan:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    env:
      REPO_AEGIS_ASSUME_PUBLIC: \${{ github.event.repository.private == false && '1' || '0' }}
      REPO_AEGIS_REDACT_ATTRIBUTION: '1'
    steps:
      - name: Checkout
        uses: ${PIN_CHECKOUT}
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Node.js
        uses: ${PIN_SETUP_NODE}
        with:
          node-version: '24'
${installStep("      ")}
      - name: Scan the pushed ref
        run: repo-aegis check --push-ref "\$GITHUB_REF" --json --require-deny-set

  # Guards the gate's own configuration. A PR that adds a waiver or a path
  # exemption in the same change as the content it unblocks is the normal
  # shape, not an exotic one: the person adding the waiver is the person the
  # gate just blocked.
  #
  # IMPORTANT — this job cannot protect itself. On \`pull_request\`, GitHub runs
  # the workflow from the PR's own ref, so a PR can delete this job and it
  # simply never runs. What makes it enforceable is a REQUIRED STATUS CHECK
  # registered by name in the repository ruleset: a deleted or renamed job then
  # reads as "expected but never received" and blocks the merge. Add
  # \`config-guard\` to your required checks, and put \`.repo-aegis.yml\` and
  # \`.github/\` under CODEOWNERS. Without that, this job is advisory only.
  config-guard:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    env:
      REPO_AEGIS_REDACT_ATTRIBUTION: '1'
      BASE_REF: \${{ github.event.pull_request.base.ref }}
    steps:
      - name: Checkout
        uses: ${PIN_CHECKOUT}
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Detect changes to the gate's configuration
        id: detect
        # BASE_REF comes in via env, never spliced into the script: a branch
        # name is attacker-controlled on a fork PR.
        run: |
          set -euo pipefail
          git fetch --no-tags --depth=1 origin "\$BASE_REF"
          changed=\$(git diff --name-only FETCH_HEAD...HEAD -- \\
            .repo-aegis.yml '.github/workflows/leak-scan*.yml' || true)
          if [ -n "\$changed" ]; then
            echo "touched=true" >> "\$GITHUB_OUTPUT"
            echo "This PR modifies the leak gate's own configuration:"
            echo "\$changed"
          else
            echo "touched=false" >> "\$GITHUB_OUTPUT"
          fi
      - name: Set up Node.js
        if: steps.detect.outputs.touched == 'true'
        uses: ${PIN_SETUP_NODE}
        with:
          node-version: '24'
${installStep("      ")}
      - name: Re-scan with every suppression ignored
        if: steps.detect.outputs.touched == 'true'
        # Reports what the proposed configuration would hide. Exit 1 here means
        # the change suppresses a real finding — which may be entirely correct,
        # and is exactly the decision a human reviewer should be making.
        run: |
          repo-aegis audit --json \\
            --require-deny-set \\
            --ignore-waivers \\
            --ignore-allowlist-comments \\
            --no-history \\
            --no-hooks-check
`;

const STRICT_WORKFLOW_CONTENT = `\
# Generated by \`repo-aegis install ci\` (profile: strict).
#
# The scheduled conscience. The PR gate has to honour waivers and
# \`repo-aegis: allow\` comments or it would be unusable — which means the set
# of suppressions is invisible in the only place anyone looks. Suppression
# creep is how a deny set quietly stops denying. This workflow runs weekly with
# every suppression ignored and every optional check enabled, and files the
# result as an issue rather than a red badge on a cron nobody watches.
#
# It opens issues, so it holds \`issues: write\` — which is precisely why it is
# a separate file from the PR gate rather than another job inside it. A
# PR-triggered job must never be able to reach that permission.
name: leak-scan-strict

on:
  schedule:
    # Mondays, 06:17 UTC. Off the hour on purpose: scheduled workflows queue
    # against everyone else's :00 cron.
    - cron: '17 6 * * 1'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: leak-scan-strict
  cancel-in-progress: false

jobs:
  strict-audit:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      issues: write
    env:
      REPO_AEGIS_ASSUME_PUBLIC: \${{ github.event.repository.private == false && '1' || '0' }}
      # An issue body is a publication channel. On a public repo it is
      # world-readable and indexed; engagement ids must not reach it.
      REPO_AEGIS_REDACT_ATTRIBUTION: '1'
    steps:
      - name: Checkout
        uses: ${PIN_CHECKOUT}
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Node.js
        uses: ${PIN_SETUP_NODE}
        with:
          node-version: '24'
${installStep("      ")}
      - name: Strict audit
        id: audit
        # --ignore-waivers + --ignore-allowlist-comments: report everything the
        # day-to-day gate suppresses. --history sweeps the full git log.
        # Written to a file rather than a step output so no scanner-derived
        # text is ever interpolated into a later shell or expression.
        run: |
          set -o pipefail
          repo-aegis audit --json \\
            --require-deny-set \\
            --ignore-waivers \\
            --ignore-allowlist-comments \\
            --history \\
            --no-hooks-check \\
            > "\$RUNNER_TEMP/strict-audit.json" && rc=0 || rc=\$?
          echo "exit-code=\$rc" >> "\$GITHUB_OUTPUT"
          exit 0
      - name: Open or update the tracking issue
        if: steps.audit.outputs.exit-code != '0'
        uses: ${PIN_GITHUB_SCRIPT}
        env:
          AUDIT_EXIT: \${{ steps.audit.outputs.exit-code }}
        with:
          script: |
            const fs = require('fs');
            const TITLE = 'repo-aegis: strict audit findings';
            // Read from disk, never from an expression: the payload contains
            // repo-derived paths and must not be spliced into anything.
            let raw = '';
            try {
              raw = fs.readFileSync(process.env.RUNNER_TEMP + '/strict-audit.json', 'utf8');
            } catch {
              raw = '(no JSON payload produced)';
            }
            const MAX = 55000;
            const body = [
              '## repo-aegis strict audit',
              '',
              'Ran with \`--ignore-waivers --ignore-allowlist-comments --history\`:',
              'this is what the day-to-day gate is currently suppressing.',
              '',
              'Exit code: \`' + process.env.AUDIT_EXIT + '\`',
              '',
              'Attribution is redacted — engagement ids are never published here.',
              'Re-run locally without \`--redact-attribution\` to see which',
              'engagement each finding belongs to.',
              '',
              '<details><summary>Findings (JSON)</summary>',
              '',
              '\`\`\`json',
              raw.length > MAX ? raw.slice(0, MAX) + '\\n... (truncated)' : raw,
              '\`\`\`',
              '',
              '</details>',
              '',
              'Run: ' + context.serverUrl + '/' + context.repo.owner + '/' +
                context.repo.repo + '/actions/runs/' + context.runId,
            ].join('\\n');

            const existing = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'repo-aegis',
            });
            const match = existing.data.find(i => i.title === TITLE);
            if (match) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: match.number,
                body,
              });
            } else {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: TITLE,
                labels: ['repo-aegis'],
                body,
              });
            }
`;

interface WorkflowSpec {
  readonly profile: CiProfile;
  readonly path: string;
  readonly content: string;
}

function workflowSpecs(): readonly WorkflowSpec[] {
  return [
    { profile: "pr", path: PR_WORKFLOW_PATH, content: PR_WORKFLOW_CONTENT },
    { profile: "strict", path: STRICT_WORKFLOW_PATH, content: STRICT_WORKFLOW_CONTENT },
  ];
}

/**
 * sha256 of every workflow body this CLI has ever written verbatim, keyed by
 * the path it was written to. `--uninstall` will only delete a file whose body
 * matches one of these — anything else is user-modified, and `WORKFLOW_MODIFIED`
 * is returned so the user decides.
 *
 * WHEN A TEMPLATE CHANGES, PREPEND THE OLD CONTENT'S HASH. Skipping that step
 * silently orphans every previously-installed copy from `--uninstall`: the
 * file stops being recognised as ours, and the user is told to delete by hand
 * a file they never wrote. `install-ci.test.ts` pins each historical hash so
 * the omission fails a test rather than shipping.
 */
const KNOWN_WORKFLOW_HASHES: Record<string, readonly string[]> = {
  [PR_WORKFLOW_PATH]: [
    // Pre-H2: no --no-hooks-check flag on the audit line (the hooks liveness
    // check didn't exist yet).
    "5385626804502467fd7d5a992557358653e3ebdf1627cc6551210f62fc2407e5",
    // 0.7.x: single-job template, actions/checkout@v4 + setup-node@v4 on Node
    // 20, no timeouts, unpinned global install, lockfile check disabled.
    // Superseded by the 0.8.0 hardening (SHA pins, Node 24, fail-closed deny
    // set, attribution redaction, tag + config-guard jobs).
    "98b6999da2a64241763ac731bcc29df52f36a7015f1b564269219d8bf1a6ab26",
    hashContent(PR_WORKFLOW_CONTENT),
  ],
  [STRICT_WORKFLOW_PATH]: [hashContent(STRICT_WORKFLOW_CONTENT)],
};

function hashContent(s: string): string {
  return createHash("sha256").update(s, "utf8").digest("hex");
}

/**
 * A `dependabot.yml` fragment that keeps the SHA pins above from rotting.
 * Printed alongside the workflow rather than written: a consumer may already
 * have a dependabot config, and silently overwriting it would be worse than
 * asking.
 */
export function dependabotFragment(): string {
  return `\
# Add to .github/dependabot.yml so the SHA pins in the generated leak-scan
# workflows stay current. Without this, pinning trades a supply-chain hole for
# a staleness problem; with it, you get neither.
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
`;
}

interface InstallCiOptions extends OutputOptions {
  cwd?: string;
  write?: boolean;
  force?: boolean;
  /**
   * Which workflow(s) to act on. Defaults to `pr` for install (the blocking
   * gate is what almost everyone wants first) and to every profile for
   * `--uninstall` (leaving a file behind would break the standing rule that
   * every install path has an opposite).
   */
  profile?: CiProfile | "all";
  /**
   * Reverse the install: delete the workflow file(s) at the canonical path if
   * (and only if) the body matches a known-emitted template. A user-modified
   * file is preserved and `WORKFLOW_MODIFIED` is surfaced. A missing file is a
   * silent no-op.
   */
  uninstall?: boolean;
  /**
   * Suppress stdout/stderr emission. emitError still fires on hard failure.
   * Used by the top-level `repo-aegis uninstall` so it can orchestrate without
   * polluting its own output.
   */
  silent?: boolean;
}

function selectedSpecs(opts: InstallCiOptions): readonly WorkflowSpec[] {
  const all = workflowSpecs();
  const requested = opts.profile ?? (opts.uninstall ? "all" : "pr");
  if (requested === "all") return all;
  const found = all.filter(s => s.profile === requested);
  if (found.length === 0) {
    emitError(
      {
        code: "UNKNOWN_PROFILE",
        error: `unknown --profile "${requested}"; expected one of: pr, strict, all`,
      },
      opts,
    );
  }
  return found;
}

export function installCi(opts: InstallCiOptions): void {
  const cwd = opts.cwd ?? process.cwd();
  const specs = selectedSpecs(opts);

  if (opts.uninstall) {
    uninstallCi(cwd, specs, opts);
    return;
  }

  if (!opts.write) {
    if (opts.json) {
      emitJson({
        action: "install-ci",
        profile: opts.profile ?? "pr",
        wrote: false,
        // Keyed by destination path so a caller (and the workflow-hygiene
        // test) can lint exactly what a consumer would receive.
        templates: Object.fromEntries(specs.map(s => [s.path, s.content])),
        dependabot: dependabotFragment(),
        // Retained for single-profile callers that predate `templates`.
        ...(specs.length === 1 && { target: join(cwd, specs[0]!.path), content: specs[0]!.content }),
      });
      return;
    }
    for (const s of specs) process.stdout.write(s.content);
    return;
  }

  const written: string[] = [];
  for (const spec of specs) {
    const target = join(cwd, spec.path);
    if (existsSync(target) && !opts.force) {
      emitError(
        {
          code: "WORKFLOW_EXISTS",
          error: `${spec.path} already exists; pass --force to overwrite`,
          details: target,
        },
        opts,
      );
    }
    const overwritten = existsSync(target);
    try {
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, spec.content);
    } catch (err) {
      emitError(
        { code: "FS_ERROR", error: `failed to write workflow: ${(err as Error).message}` },
        opts,
      );
    }
    written.push(target);

    // Audit (best-effort). Emit AFTER the workflow file is written.
    try {
      appendAuditRecord({
        action: "install-ci",
        cwd,
        repo: cwd,
        details: { target, profile: spec.profile, force: !!opts.force, overwritten },
      });
    } catch {
      /* audit log must not break user-facing ops */
    }
  }

  if (opts.json) {
    // Same compatibility rule as uninstall: `target` and `wrote` keep their
    // pre-0.8.0 types; `targets` carries the multi-profile case.
    emitJson({
      action: "install-ci",
      profile: opts.profile ?? "pr",
      wrote: true,
      target: written[0] ?? null,
      targets: written,
      overwritten: !!opts.force,
    });
    return;
  }
  for (const t of written) emitText(`wrote ${t}`);
  emitText("");
  emitText("Next, so the pins in these workflows do not go stale, add to .github/dependabot.yml:");
  emitText("");
  process.stdout.write(dependabotFragment());
}

function uninstallCi(cwd: string, specs: readonly WorkflowSpec[], opts: InstallCiOptions): void {
  const removed: string[] = [];
  const absent: string[] = [];

  for (const spec of specs) {
    const target = join(cwd, spec.path);
    if (!existsSync(target)) {
      absent.push(target);
      continue;
    }

    let body: string;
    try {
      body = readFileSync(target, "utf8");
    } catch (err) {
      emitError(
        { code: "FS_ERROR", error: `failed to read ${target}: ${(err as Error).message}` },
        opts,
      );
    }
    const hash = hashContent(body!);
    const known = (KNOWN_WORKFLOW_HASHES[spec.path] ?? []).includes(hash);

    if (!known) {
      emitError(
        {
          code: "WORKFLOW_MODIFIED",
          error:
            `${spec.path} differs from any known repo-aegis-emitted template; ` +
            `refusing to delete. If you're sure, remove the file manually: \`rm ${target}\`.`,
          details: target,
        },
        opts,
      );
    }

    try {
      unlinkSync(target);
    } catch (err) {
      emitError(
        { code: "FS_ERROR", error: `failed to remove ${target}: ${(err as Error).message}` },
        opts,
      );
    }
    removed.push(target);

    try {
      appendAuditRecord({
        action: "uninstall-ci",
        cwd,
        repo: cwd,
        details: { target, profile: spec.profile, hash },
      });
    } catch {
      /* audit log must not break user-facing ops */
    }
  }

  if (opts.silent) return;
  if (opts.json) {
    // `target` / `removed` / `absent` keep their pre-0.8.0 types (path string,
    // booleans) because they are a documented JSON contract. Multi-file runs
    // are described by the new `removedPaths` / `absentPaths` arrays; the
    // scalars describe the first file acted on, which for the overwhelmingly
    // common single-profile call is the only one.
    emitJson({
      action: "uninstall-ci",
      target: removed[0] ?? absent[0] ?? null,
      removed: removed.length > 0,
      ...(removed.length === 0 && absent.length > 0 && { absent: true }),
      removedPaths: removed,
      absentPaths: absent,
    });
    return;
  }
  for (const t of removed) emitText(`removed ${t}`);
  for (const t of absent) emitText(`${t} not present (nothing to remove)`);
}
