// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Richard Myers and contributors.
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { appendAuditRecord } from "@de-otio/repo-aegis-core";
import { emitJson, emitText, emitError, type OutputOptions } from "../format.js";

const WORKFLOW_PATH_REL = ".github/workflows/leak-scan.yml";

const WORKFLOW_CONTENT = `\
# Generated by \`repo-aegis install ci\`.
# Scans the repository for engagement-scoped marker hits on every PR
# and on direct pushes to main/master. Runs \`repo-aegis audit\` once
# in marker-scan-only mode (history/lockfile/fixture/remote checks
# disabled) so the cost is a single node process per CI run rather
# than one process per tracked file. To enable the other audit
# checks, remove the corresponding --no-* flags below.
name: leak-scan
on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  leak-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install repo-aegis
        run: npm install -g @de-otio/repo-aegis
      - name: Marker scan
        # audit's JSON output enumerates findings per check with file:line,
        # so a non-zero exit identifies the offending file without a
        # per-file echo loop. Hooks must never pass --verbose; the CI
        # runner is no different — keep marker output redacted in logs.
        run: repo-aegis audit --json --no-history --no-lockfile-check --no-fixture-check --no-remote-check
`;

interface InstallCiOptions extends OutputOptions {
  cwd?: string;
  write?: boolean;
  force?: boolean;
}

export function installCi(opts: InstallCiOptions): void {
  const cwd = opts.cwd ?? process.cwd();
  const target = join(cwd, WORKFLOW_PATH_REL);

  if (!opts.write) {
    if (opts.json) {
      emitJson({
        action: "install-ci",
        target,
        wrote: false,
        content: WORKFLOW_CONTENT,
      });
      return;
    }
    process.stdout.write(WORKFLOW_CONTENT);
    return;
  }

  if (existsSync(target) && !opts.force) {
    emitError(
      {
        code: "WORKFLOW_EXISTS",
        error: `${WORKFLOW_PATH_REL} already exists; pass --force to overwrite`,
        details: target,
      },
      opts,
    );
  }

  try {
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, WORKFLOW_CONTENT);
  } catch (err) {
    emitError(
      { code: "FS_ERROR", error: `failed to write workflow: ${(err as Error).message}` },
      opts,
    );
  }

  // Audit (best-effort). Emit AFTER the workflow file is written.
  try {
    appendAuditRecord({
      action: "install-ci",
      cwd,
      repo: cwd,
      details: { target, force: !!opts.force },
    });
  } catch {
    /* audit log must not break user-facing ops */
  }

  if (opts.json) {
    emitJson({
      action: "install-ci",
      target,
      wrote: true,
      overwritten: existsSync(target) && !!opts.force,
    });
    return;
  }
  emitText(`wrote ${target}`);
}
