import { mkdirSync, writeFileSync, chmodSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join } from "node:path";
import { repoAegisHome } from "@de-otio/repo-aegis-core";
import { emitJson, emitText, emitError, type OutputOptions } from "../format.js";

const PRE_COMMIT_SCRIPT = `\
#!/usr/bin/env bash
# Generated by \`repo-aegis install hooks\`. Do not edit; this file is
# overwritten on every \`install hooks\` run. The source of truth lives in
# packages/cli/src/commands/install-hooks.ts (PRE_COMMIT_SCRIPT constant).
#
# Fail-open if repo-aegis is not on PATH so the git workflow doesn't
# break for users who haven't yet installed the CLI globally.
set -euo pipefail

if ! command -v repo-aegis >/dev/null 2>&1; then
  exit 0
fi

# Never pass --verbose: hook output flows into the agent's tool result
# and must not echo literal markers.
exec repo-aegis check --staged
`;

const PRE_PUSH_SCRIPT = `\
#!/usr/bin/env bash
# Generated by \`repo-aegis install hooks\`. Do not edit; see install-hooks.ts.
#
# Reads stdin lines of \`<local-ref> <local-sha> <remote-ref> <remote-sha>\`
# and runs \`repo-aegis check --range\` per updated branch. New branches
# scan the full local sha; deletions skip.
set -euo pipefail

if ! command -v repo-aegis >/dev/null 2>&1; then
  exit 0
fi

zero="0000000000000000000000000000000000000000"
exit_rc=0
while read -r local_ref local_sha remote_ref remote_sha; do
  : "$local_ref" "$remote_ref"
  if [ "$local_sha" = "$zero" ]; then
    continue
  fi
  if [ "$remote_sha" = "$zero" ]; then
    range="$local_sha"
  else
    range="\${remote_sha}..\${local_sha}"
  fi
  if ! repo-aegis check --range "$range"; then
    exit_rc=1
  fi
done

exit "$exit_rc"
`;

interface InstallHooksOptions extends OutputOptions {
  force?: boolean;
  cwd?: string;
}

function git(cwd: string, args: string[]): { ok: boolean; stdout: string } {
  try {
    const stdout = execFileSync("git", args, {
      cwd,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    return { ok: true, stdout };
  } catch {
    return { ok: false, stdout: "" };
  }
}

export function installHooks(opts: InstallHooksOptions): void {
  const cwd = opts.cwd ?? process.cwd();

  const inside = git(cwd, ["rev-parse", "--is-inside-work-tree"]);
  if (!inside.ok || inside.stdout !== "true") {
    emitError({ code: "NOT_GIT_REPO", error: "not inside a git repository" }, opts);
  }

  const hooksDir = join(repoAegisHome(), "hooks");
  const preCommitPath = join(hooksDir, "pre-commit");
  const prePushPath = join(hooksDir, "pre-push");

  const existing = git(cwd, ["config", "--get", "core.hooksPath"]);
  const previousHooksPath = existing.ok ? existing.stdout : "";
  const conflict = previousHooksPath !== "" && previousHooksPath !== hooksDir;

  if (conflict && !opts.force) {
    emitError(
      {
        code: "HOOKS_PATH_CONFLICT",
        error: "core.hooksPath is already set to a different path",
        details: `current: ${previousHooksPath}\n  target: ${hooksDir}\n  pass --force to overwrite`,
      },
      opts,
    );
  }

  try {
    mkdirSync(hooksDir, { recursive: true, mode: 0o700 });
    try {
      chmodSync(hooksDir, 0o700);
    } catch {
      /* platform-restricted */
    }

    writeFileSync(preCommitPath, PRE_COMMIT_SCRIPT, { mode: 0o755 });
    chmodSync(preCommitPath, 0o755);

    writeFileSync(prePushPath, PRE_PUSH_SCRIPT, { mode: 0o755 });
    chmodSync(prePushPath, 0o755);
  } catch (err) {
    emitError(
      { code: "FS_ERROR", error: `failed to write hook scripts: ${(err as Error).message}` },
      opts,
    );
  }

  try {
    execFileSync("git", ["config", "core.hooksPath", hooksDir], {
      cwd,
      stdio: ["ignore", "ignore", "ignore"],
    });
  } catch (err) {
    emitError(
      { code: "GIT_CONFIG_ERROR", error: `failed to set core.hooksPath: ${(err as Error).message}` },
      opts,
    );
  }

  if (opts.json) {
    emitJson({
      action: "install-hooks",
      hooksDir,
      installed: ["pre-commit", "pre-push"],
      coreHooksPath: hooksDir,
      previousCoreHooksPath: previousHooksPath || null,
      overwritten: conflict,
    });
    return;
  }

  emitText(`installed hooks at ${hooksDir}`);
  emitText(`set core.hooksPath = ${hooksDir}`);
  if (conflict) {
    emitText(`  (previous value: ${previousHooksPath} — overwritten with --force)`);
  }
}
