import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { emitJson, emitText, emitError, type OutputOptions } from "../format.js";

const WORKFLOW_PATH_REL = ".github/workflows/leak-scan.yml";

const WORKFLOW_CONTENT = `\
# Generated by \`repo-aegis install ci\`.
# Scans the repository for engagement-scoped marker hits on every PR
# and on direct pushes to main/master. Tracked files are scanned
# individually via \`repo-aegis check --path\`; non-zero exit fails
# the job.
name: leak-scan
on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  leak-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install repo-aegis
        run: npm install -g @de-otio/repo-aegis
      - name: Scan tracked files
        run: |
          set -euo pipefail
          # Scan every tracked file. Hooks must never pass --verbose; the
          # CI runner is no different — keep marker output redacted in logs.
          rc=0
          while IFS= read -r f; do
            if [ -f "$f" ]; then
              repo-aegis check --path "$f" --json || rc=$?
            fi
          done < <(git ls-files)
          exit "$rc"
`;

interface InstallCiOptions extends OutputOptions {
  cwd?: string;
  write?: boolean;
  force?: boolean;
}

export function installCi(opts: InstallCiOptions): void {
  const cwd = opts.cwd ?? process.cwd();
  const target = join(cwd, WORKFLOW_PATH_REL);

  if (!opts.write) {
    if (opts.json) {
      emitJson({
        action: "install-ci",
        target,
        wrote: false,
        content: WORKFLOW_CONTENT,
      });
      return;
    }
    process.stdout.write(WORKFLOW_CONTENT);
    return;
  }

  if (existsSync(target) && !opts.force) {
    emitError(
      {
        code: "WORKFLOW_EXISTS",
        error: `${WORKFLOW_PATH_REL} already exists; pass --force to overwrite`,
        details: target,
      },
      opts,
    );
  }

  try {
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, WORKFLOW_CONTENT);
  } catch (err) {
    emitError(
      { code: "FS_ERROR", error: `failed to write workflow: ${(err as Error).message}` },
      opts,
    );
  }

  if (opts.json) {
    emitJson({
      action: "install-ci",
      target,
      wrote: true,
      overwritten: existsSync(target) && !!opts.force,
    });
    return;
  }
  emitText(`wrote ${target}`);
}
