import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  appendFileSync,
  chmodSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { leakContextFlagPath } from "@de-otio/repo-aegis-core";
import { emitJson, emitText, emitError, type OutputOptions } from "../format.js";

const CLAUDE_MD_BEGIN = "<!-- repo-aegis: managed block — do not edit between markers -->";
const CLAUDE_MD_END = "<!-- repo-aegis: end managed block -->";

const CLAUDE_MD_BLOCK = `${CLAUDE_MD_BEGIN}
## repo-aegis (data-leak prevention)

This machine is configured with [repo-aegis](https://github.com/de-otio/repo-aegis)
for engagement-scoped data-leak prevention. A PostToolUse hook scans
files written by Write/Edit/MultiEdit against this repo's scoped deny
set. If the agent receives a tool result with a marker hit, it must:

- Not echo the literal marker back to the user.
- Not retry the write with the marker still present.
- Surface the hit to the user, propose a redaction, and wait for confirmation.

If a marker is hit, run \`repo-aegis status\` (without \`--verbose\`) to
see the repo's class, allowed engagements, and deny-set summary.
${CLAUDE_MD_END}
`;

const SCAN_AFTER_WRITE_SCRIPT = `\
#!/usr/bin/env bash
# Generated by \`repo-aegis install claude-md\`. Do not edit; see
# packages/cli/src/commands/install-claude-md.ts (SCAN_AFTER_WRITE_SCRIPT).
#
# Claude Code PostToolUse hook for Write/Edit/MultiEdit. Reads the
# tool-result JSON on stdin, extracts the file_path, and runs
# \`repo-aegis check --path\` on it. Output flows back into the agent's
# tool result.
#
# Critically, NEVER passes --verbose: literal markers in tool result is
# the recency-pressure failure mode the tool exists to prevent.
set -euo pipefail

if ! command -v repo-aegis >/dev/null 2>&1; then
  exit 0
fi
if ! command -v jq >/dev/null 2>&1; then
  exit 0
fi

input=$(cat)
file_path=$(echo "$input" | jq -r '.tool_input.file_path // .tool_input.path // empty')

if [ -z "$file_path" ] || [ ! -f "$file_path" ]; then
  exit 0
fi

# The agent supplies file_path; treat it strictly as a value, never a flag.
# Use the \`--path=VALUE\` form so a path beginning with \`-\` cannot inject
# CLI flags (e.g. \`--verbose\` would otherwise enable literal-reveal).
out=$(repo-aegis check --json --path="$file_path" 2>&1 || true)

if [ -n "$out" ]; then
  echo "$out"
fi
`;

interface InstallClaudeMdOptions extends OutputOptions {
  claudeHome?: string;
  /**
   * When true, do the work but suppress all stdout/stderr emission.
   * emitError still fires on hard failure. Used by `init`.
   */
  silent?: boolean;
  /**
   * When true, perform the merge in-memory and print the would-be
   * settings.json plus the would-be CLAUDE.md additions to stdout
   * instead of writing anything to disk. Useful for previewing the
   * effect of `install claude-md` before committing to it. Aliased
   * as --print-only on the CLI.
   */
  dryRun?: boolean;
}

interface SettingsJson {
  hooks?: Record<string, HookMatcherEntry[]>;
  [k: string]: unknown;
}

interface HookMatcherEntry {
  matcher?: string;
  hooks?: HookCommand[];
}

interface HookCommand {
  type?: string;
  command?: string;
}

const HOOK_MATCHER = "Write|Edit|MultiEdit";

function defaultClaudeHome(): string {
  return join(homedir(), ".claude");
}

function readSettings(path: string): SettingsJson {
  if (!existsSync(path)) return {};
  const raw = readFileSync(path, "utf8");
  if (raw.trim() === "") return {};
  try {
    return JSON.parse(raw) as SettingsJson;
  } catch (err) {
    throw new Error(`failed to parse ${path}: ${(err as Error).message}`);
  }
}

interface MergeResult {
  added: boolean;
  alreadyPresent: boolean;
}

function mergeHook(settings: SettingsJson, hookCommand: string): MergeResult {
  if (!settings.hooks) settings.hooks = {};
  if (!settings.hooks["PostToolUse"]) settings.hooks["PostToolUse"] = [];

  const post = settings.hooks["PostToolUse"]!;

  let entry = post.find(e => e.matcher === HOOK_MATCHER);
  if (!entry) {
    entry = { matcher: HOOK_MATCHER, hooks: [] };
    post.push(entry);
  }
  if (!entry.hooks) entry.hooks = [];

  const exists = entry.hooks.some(
    h => h.type === "command" && h.command === hookCommand,
  );
  if (exists) {
    return { added: false, alreadyPresent: true };
  }
  entry.hooks.push({ type: "command", command: hookCommand });
  return { added: true, alreadyPresent: false };
}

export function installClaudeMd(opts: InstallClaudeMdOptions): void {
  const claudeHome = opts.claudeHome ?? defaultClaudeHome();
  const claudeMdPath = join(claudeHome, "CLAUDE.md");
  const hooksDir = join(claudeHome, "hooks");
  const scriptPath = join(hooksDir, "scan-after-write.sh");
  const settingsPath = join(claudeHome, "settings.json");

  if (opts.dryRun) {
    dryRunInstallClaudeMd({
      claudeHome,
      claudeMdPath,
      hooksDir,
      scriptPath,
      settingsPath,
      opts,
    });
    return;
  }

  try {
    mkdirSync(claudeHome, { recursive: true });
    mkdirSync(hooksDir, { recursive: true });
  } catch (err) {
    emitError(
      { code: "FS_ERROR", error: `failed to create ${claudeHome}: ${(err as Error).message}` },
      opts,
    );
  }

  // 1. CLAUDE.md snippet (idempotent via marker comment)
  let claudeMdAppended = false;
  let claudeMdAlreadyPresent = false;
  let existingClaudeMd = "";
  if (existsSync(claudeMdPath)) existingClaudeMd = readFileSync(claudeMdPath, "utf8");

  if (existingClaudeMd.includes(CLAUDE_MD_BEGIN)) {
    claudeMdAlreadyPresent = true;
  } else {
    const needsLeadingNewline =
      existingClaudeMd.length > 0 && !existingClaudeMd.endsWith("\n");
    const prefix = existingClaudeMd.length === 0 ? "" : (needsLeadingNewline ? "\n\n" : "\n");
    if (existsSync(claudeMdPath)) {
      appendFileSync(claudeMdPath, prefix + CLAUDE_MD_BLOCK);
    } else {
      writeFileSync(claudeMdPath, CLAUDE_MD_BLOCK);
    }
    claudeMdAppended = true;
  }

  // 2. Write the scan-after-write script (overwrite is fine; it's our content)
  try {
    writeFileSync(scriptPath, SCAN_AFTER_WRITE_SCRIPT, { mode: 0o755 });
    chmodSync(scriptPath, 0o755);
  } catch (err) {
    emitError(
      { code: "FS_ERROR", error: `failed to write ${scriptPath}: ${(err as Error).message}` },
      opts,
    );
  }

  // 3. Merge into settings.json
  let settings: SettingsJson;
  try {
    settings = readSettings(settingsPath);
  } catch (err) {
    emitError(
      { code: "SETTINGS_PARSE_ERROR", error: (err as Error).message },
      opts,
    );
  }
  const merge = mergeHook(settings!, scriptPath);

  if (merge.added) {
    try {
      writeFileSync(settingsPath, JSON.stringify(settings!, null, 2) + "\n");
    } catch (err) {
      emitError(
        { code: "FS_ERROR", error: `failed to write ${settingsPath}: ${(err as Error).message}` },
        opts,
      );
    }
  }

  // 4. Warn if leak-context strict mode is off
  const flagPath = leakContextFlagPath();
  const strictModeOn = existsSync(flagPath);

  if (opts.silent) return;

  if (opts.json) {
    emitJson({
      action: "install-claude-md",
      claudeHome,
      claudeMd: { path: claudeMdPath, appended: claudeMdAppended, alreadyPresent: claudeMdAlreadyPresent },
      hookScript: { path: scriptPath, written: true },
      settings: { path: settingsPath, added: merge.added, alreadyPresent: merge.alreadyPresent },
      strictModeOn,
    });
    return;
  }

  if (claudeMdAppended) emitText(`appended snippet to ${claudeMdPath}`);
  else emitText(`snippet already present in ${claudeMdPath}`);
  emitText(`wrote ${scriptPath}`);
  if (merge.added) emitText(`registered PostToolUse hook in ${settingsPath}`);
  else emitText(`PostToolUse hook already registered in ${settingsPath}`);
  if (!strictModeOn) {
    emitText("");
    emitText("note: leak-context strict mode is OFF.");
    emitText("  enable for sensitive sessions: repo-aegis context on");
  }
}

interface DryRunContext {
  claudeHome: string;
  claudeMdPath: string;
  hooksDir: string;
  scriptPath: string;
  settingsPath: string;
  opts: InstallClaudeMdOptions;
}

function dryRunInstallClaudeMd(ctx: DryRunContext): void {
  const { claudeHome, claudeMdPath, hooksDir, scriptPath, settingsPath, opts } = ctx;

  // 1. CLAUDE.md — compute would-be additions without writing.
  let existingClaudeMd = "";
  if (existsSync(claudeMdPath)) existingClaudeMd = readFileSync(claudeMdPath, "utf8");

  const claudeMdAlreadyPresent = existingClaudeMd.includes(CLAUDE_MD_BEGIN);
  let claudeMdAddition = "";
  if (!claudeMdAlreadyPresent) {
    const needsLeadingNewline =
      existingClaudeMd.length > 0 && !existingClaudeMd.endsWith("\n");
    const prefix =
      existingClaudeMd.length === 0 ? "" : (needsLeadingNewline ? "\n\n" : "\n");
    claudeMdAddition = prefix + CLAUDE_MD_BLOCK;
  }

  // 2. settings.json — compute the merged JSON in memory.
  let settings: SettingsJson;
  try {
    settings = readSettings(settingsPath);
  } catch (err) {
    emitError(
      { code: "SETTINGS_PARSE_ERROR", error: (err as Error).message },
      opts,
    );
    return;
  }
  // mergeHook mutates settings in place; that's fine here because
  // `settings` is a fresh object parsed inside this function and is
  // not persisted.
  const merge = mergeHook(settings, scriptPath);
  const wouldBeSettings = JSON.stringify(settings, null, 2) + "\n";

  // 3. strict-mode flag (read-only check)
  const flagPath = leakContextFlagPath();
  const strictModeOn = existsSync(flagPath);

  if (opts.silent) return;

  if (opts.json) {
    emitJson({
      action: "install-claude-md",
      dryRun: true,
      claudeHome,
      claudeMd: {
        path: claudeMdPath,
        wouldAppend: !claudeMdAlreadyPresent,
        alreadyPresent: claudeMdAlreadyPresent,
        addition: claudeMdAddition,
      },
      hookScript: {
        path: scriptPath,
        hooksDir,
        wouldWrite: true,
        contents: SCAN_AFTER_WRITE_SCRIPT,
      },
      settings: {
        path: settingsPath,
        wouldAdd: merge.added,
        alreadyPresent: merge.alreadyPresent,
        contents: wouldBeSettings,
      },
      strictModeOn,
    });
    return;
  }

  emitText("# repo-aegis install claude-md (dry run — nothing written)");
  emitText("");
  emitText(`# Would-be CLAUDE.md additions to: ${claudeMdPath}`);
  if (claudeMdAlreadyPresent) {
    emitText("# (managed block already present; no addition)");
  } else if (claudeMdAddition === "") {
    emitText("# (no additions needed)");
  } else {
    emitText(claudeMdAddition);
  }
  emitText("");
  emitText(`# Would-be hook script at: ${scriptPath}`);
  emitText(SCAN_AFTER_WRITE_SCRIPT);
  emitText("");
  emitText(`# Would-be settings.json at: ${settingsPath}`);
  if (merge.alreadyPresent) {
    emitText("# (PostToolUse hook already registered; settings.json unchanged)");
  }
  emitText(wouldBeSettings);
  if (!strictModeOn) {
    emitText("");
    emitText("# note: leak-context strict mode is OFF.");
    emitText("#   enable for sensitive sessions: repo-aegis context on");
  }
}
