// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Richard Myers and contributors.
//
// Text of the `gh` PATH shim. This module is the SINGLE source of truth for
// the installed script; `install-shim.ts` only writes this string to disk.
// Same arrangement as `core/src/hook-scripts.ts` and for the same reason:
// a standalone `.sh` template drifts from the code that installs it, and
// the copy that drifts is the one that stops guarding.
//
// Edit here, rebuild, and run `repo-aegis install shim` again to refresh an
// installed copy.

/**
 * First comment line of the generated script. `install shim` uses it to tell
 * its own file apart from a `gh` wrapper someone else put at the same path —
 * refusing to clobber a stranger's file is the difference between an install
 * and a footgun.
 */
export const SHIM_HEADER_LINE = "# Generated by `repo-aegis install shim`";

export const GH_SHIM_SCRIPT = `\
#!/usr/bin/env bash
${SHIM_HEADER_LINE}
# Do not edit; overwritten on every \`install shim\` run. Source of truth:
# packages/cli/src/commands/shim-script.ts (GH_SHIM_SCRIPT).
#
# A PATH shim for \`gh\` (doc/design/egress-guard.md §3). Reads pass through
# untouched; publishing verbs are shown to \`repo-aegis egress-check\` first.
# Every failure mode falls open to the real \`gh\` EXCEPT a deny (exit 2) and
# a confirmed read-back mismatch (exit 1): a guardrail that breaks the tool
# it wraps gets uninstalled, and an uninstalled guardrail guards nothing.
#
# Written for bash 3.2 (macOS's stock /bin/bash): no GNU-only path
# canonicalisation flags, no bash-4 array builtins, no associative arrays —
# \`cd … && pwd -P\` does the canonicalising instead. \`set -e\` is deliberately
# NOT used: this script reads exit codes itself and must not die on the first
# non-zero one.
set -u

__repo_aegis_same_file() {
  [ -e "\$1" ] && [ -e "\$2" ] || return 1
  local a b
  a="\$(cd "\$(dirname "\$1")" 2>/dev/null && pwd -P)/\$(basename "\$1")"
  b="\$(cd "\$(dirname "\$2")" 2>/dev/null && pwd -P)/\$(basename "\$2")"
  [ "\$a" = "\$b" ]
}

# --- 1. Locate the real \`gh\` ------------------------------------------------
# The first executable \`gh\` on PATH that is neither inside this shim's own
# directory nor the same file as this shim. Comparing CANONICAL paths, not
# names, is what makes self-recursion impossible even when the shim is
# reached through a symlink or a relative PATH entry. There is no hard-coded
# fallback path: a wrong guess would silently bypass the user's own \`gh\`.
__ra_self_dir="\$(cd "\$(dirname "\$0")" 2>/dev/null && pwd -P)"
__ra_self="\${__ra_self_dir}/\$(basename "\$0")"

__ra_real_gh=""
__ra_saved_ifs="\$IFS"
set -f
IFS=":"
for __ra_dir in \$PATH; do
  [ -n "\$__ra_dir" ] || __ra_dir="."
  __ra_cand="\${__ra_dir}/gh"
  [ -f "\$__ra_cand" ] && [ -x "\$__ra_cand" ] || continue
  __ra_cand_dir="\$(cd "\$__ra_dir" 2>/dev/null && pwd -P)" || continue
  [ "\$__ra_cand_dir" = "\$__ra_self_dir" ] && continue
  __repo_aegis_same_file "\$__ra_cand" "\$__ra_self" && continue
  __ra_real_gh="\$__ra_cand"
  break
done
IFS="\$__ra_saved_ifs"
set +f

if [ -z "\$__ra_real_gh" ]; then
  echo "repo-aegis shim: real gh not found on PATH" >&2
  exit 127
fi

# --- 2. Pre-filter ----------------------------------------------------------
# Cheap, in bash, before paying for a node start-up: only the \`gh\` groups
# that can publish reach the decision call. Everything else — \`--version\`,
# \`auth\`, \`browse\`, \`status\`, completion — is exec'd with argv untouched.
#
# Trade-off, stated deliberately: reads INSIDE these groups (\`gh pr view\`,
# \`gh api\` GETs, \`gh run list\`) still reach step 3 and pay one
# \`repo-aegis\` invocation. egress-check returns allow for them — they carry
# no egress intent — so the cost is latency, not behaviour. Filtering harder
# here would mean a second copy of the verb table in bash, and the copy that
# drifts is the one that stops guarding.
case "\${1:-}" in
  pr|issue|release|repo|api|gist|workflow|run|secret|variable|label|ruleset) ;;
  *) exec "\$__ra_real_gh" "\$@" ;;
esac

# Fail open when the CLI is not installed, exactly like the git hooks.
if ! command -v repo-aegis >/dev/null 2>&1; then
  exec "\$__ra_real_gh" "\$@"
fi

# --- 3. The decision --------------------------------------------------------
# stdout is captured (it is the machine-readable verdict); stderr is left
# alone so the deny reason and the receipt reach the terminal and the agent's
# tool result. Exit 2 = deny, and the reason is already on stderr. Any other
# non-zero exit is a fault in the guard itself, which must not block \`gh\`.
__ra_out="\$(repo-aegis egress-check --cwd "\$PWD" -- "\$@")"
__ra_rc=\$?
if [ "\$__ra_rc" -eq 2 ]; then
  exit 2
fi
if [ "\$__ra_rc" -ne 0 ]; then
  echo "repo-aegis shim: egress-check failed (rc=\$__ra_rc); proceeding" >&2
fi

# --- 4. Run it --------------------------------------------------------------
# A \`pr create|edit\` that publishes a body FILE gets the body read back
# afterwards. The verb has already published by then, so the read-back cannot
# block anything; it only makes a wrong body loud within seconds instead of
# invisible for an hour.
case "\$__ra_out" in
  *'"readback"'*) ;;
  *) exec "\$__ra_real_gh" "\$@" ;;
esac

__ra_body_file="\$(printf '%s\\n' "\$__ra_out" | sed -n 's/.*"bodyFile"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p' | head -n 1)"
# A TEMPLATE, not a bare \`mktemp\`: BSD mktemp (macOS) REQUIRES one and
# fails without it, which would silently skip the read-back on every Mac.
__ra_tmp="\$(mktemp "\${TMPDIR:-/tmp}/repo-aegis-shim.XXXXXX" 2>/dev/null || true)"
if [ -z "\$__ra_body_file" ] || [ -z "\$__ra_tmp" ]; then
  exec "\$__ra_real_gh" "\$@"
fi

# NOT exec: gh's stdout is tee'd so the PR URL it prints can be handed to the
# read-back, and the user still sees it unchanged. PIPESTATUS preserves gh's
# own exit code (present in bash 3.2).
"\$__ra_real_gh" "\$@" | tee "\$__ra_tmp"
__ra_gh_rc="\${PIPESTATUS[0]}"

repo-aegis egress-readback --cwd "\$PWD" --body-file "\$__ra_body_file" --pr "\$(cat "\$__ra_tmp")" --gh "\$__ra_real_gh"
__ra_readback_rc=\$?
rm -f "\$__ra_tmp"

# A confirmed mismatch is the one post-publish condition worth failing on;
# a read-back that could not run exits 0 and changes nothing.
if [ "\$__ra_readback_rc" -ne 0 ]; then
  exit "\$__ra_readback_rc"
fi
exit "\$__ra_gh_rc"
`;
