// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Richard Myers and contributors.
//
// Hook script text. This module is the SINGLE source of truth for the
// installed scripts; `cli/commands/install-hooks.ts` imports the
// constants below rather than defining them. Keeping them in core lets
// `hooks-state.ts` compute a digest of "the script that should be on
// disk" without the core package depending on the cli package.
//
// The standalone .sh.template files were removed to eliminate drift
// (see git history); do not reintroduce them. Edit here, rebuild, run
// `install hooks` again to refresh installed copies.
import { createHash } from "node:crypto";

export type HookName = "pre-commit" | "pre-push";

// Shared by both scripts below: is $1 the same on-disk file as $2, by
// canonical path? Used to guard the chaining \`exec\` against
// self-recursion when \`core.hooksPath\` (global by default since the
// v0.7 default flip) happens to resolve to this repo's own
// \`.git/hooks\` — without this guard that config would make a hook
// exec itself forever instead of running once. Written for bash 3.2
// (macOS's stock /bin/bash) as well as bash 4/5: no \`readlink -f\`
// (GNU-only), no \`shopt -s lastpipe\` (bash 4+ only).
const SAME_FILE_HELPER = `\
__repo_aegis_same_file() {
  [ -e "$1" ] && [ -e "$2" ] || return 1
  local a b
  a="$(cd "$(dirname "$1")" 2>/dev/null && pwd -P)/$(basename "$1")"
  b="$(cd "$(dirname "$2")" 2>/dev/null && pwd -P)/$(basename "$2")"
  [ "$a" = "$b" ]
}`;

export const PRE_COMMIT_SCRIPT = `\
#!/usr/bin/env bash
# Generated by \`repo-aegis install hooks\`. Do not edit; overwritten on
# every \`install hooks\` run. Source of truth: packages/core/src/
# hook-scripts.ts (PRE_COMMIT_SCRIPT).
#
# Fail-open if repo-aegis is not on PATH so the git workflow doesn't
# break for users who haven't yet installed the CLI globally.
set -euo pipefail

if ! command -v repo-aegis >/dev/null 2>&1; then
  exit 0
fi

# Never pass --verbose: hook output flows into the agent's tool result
# and must not echo literal markers.
if ! repo-aegis check --staged; then
  # A repo-aegis hit blocks the commit outright. Do NOT fall through to
  # the chaining below: running the repo's own pre-commit afterward and
  # letting IT decide the exit code would let an exit-0 chained hook
  # silently mask this failure.
  exit 1
fi

${SAME_FILE_HELPER}

# Chain to the repo's own pre-commit hook, if one exists. Since v0.7,
# \`install hooks\` writes core.hooksPath GLOBALLY by default, which
# would otherwise silently stop any hook a human or another tool
# installed directly into this repo's \`.git/hooks\` from ever running
# again — git consults exactly one hooks directory. This is the fix:
# run ours first (above), then hand off to theirs.
# --git-common-dir (NOT --git-path hooks) is deliberate: --git-path
# hooks resolves the EFFECTIVE path, i.e. honors core.hooksPath — which
# right now is US, so it would always "find" ourselves and the
# same-file guard below would skip chaining forever. --git-common-dir
# gives the repo's real .git dir independent of any core.hooksPath
# override (and is shared across linked worktrees), which is what
# holds a hook a human or other tool installed directly.
git_common_dir="$(git rev-parse --git-common-dir 2>/dev/null || true)"
hooks_dir=""
if [ -n "$git_common_dir" ]; then
  hooks_dir="$git_common_dir/hooks"
fi
if [ -n "$hooks_dir" ]; then
  chained="$hooks_dir/pre-commit"
  if [ -x "$chained" ] && ! __repo_aegis_same_file "$chained" "$0"; then
    exec "$chained" "$@"
  fi
fi

exit 0
`;

export const PRE_PUSH_SCRIPT = `\
#!/usr/bin/env bash
# Generated by \`repo-aegis install hooks\`. Source of truth:
# packages/core/src/hook-scripts.ts (PRE_PUSH_SCRIPT).
#
# Reads stdin lines of \`<local-ref> <local-sha> <remote-ref> <remote-sha>\`
# and scans each updated ref. Branch deletions (zero local sha) skip.
#
# Two cases, because they are genuinely different questions:
#   remote_sha set   -> \`check --range <remote_sha>..<local_sha>\`: exactly
#                       the commits this push adds to a ref the remote has.
#   remote_sha zero  -> the ref is new to the remote, so there is no sha to
#                       diff against. This used to mean "diff the empty tree
#                       against the local sha", i.e. re-scan the whole
#                       reachable history — which made pushing a release tag
#                       that points at an already-pushed commit block on
#                       benign historical matches, and taught operators
#                       \`--no-verify\`. \`check --push-ref\` instead asks what
#                       the remote-tracking refs already reach and scans only
#                       the difference (nothing at all, for that tag). Set
#                       REPO_AEGIS_NEW_REF_FULL_SCAN=1 to force the old
#                       whole-history behaviour.
#
# Git passes \`<remote-name> <remote-url>\` as positional args 1 and 2. The
# remote NAME selects the refs/remotes/<name>/* namespace to compare against.
# The remote URL is the DESTINATION, and it is passed on as
# \`--remote-url\` (doc/design/egress-guard.md §2): this hook is the one place
# in the stack that sees where the bytes are going at the moment of egress,
# and ignoring \$2 is what let a bare \`git push\` in the wrong checkout publish
# a private branch to a public remote with every content check passing. With
# it, \`check\` can refuse a cross-org push (\`CROSS_ORG_PUSH\`) or an
# unattended push to a public-facing repo (\`PUBLIC_PUSH_NEEDS_HUMAN\`), and
# otherwise prints a one-line receipt naming the destination.
#
# \$2 is empty when a push names a URL that git has no remote entry for; the
# helper below then omits the flag entirely rather than passing an empty
# value, so \`check\` sees exactly the pre-egress-guard argument list.
#
# Fail-open if repo-aegis is not on PATH so the git workflow doesn't
# break for users who haven't yet installed the CLI globally.
set -euo pipefail

if ! command -v repo-aegis >/dev/null 2>&1; then
  exit 0
fi

${SAME_FILE_HELPER}

zero="0000000000000000000000000000000000000000"
remote_name="\${1:-origin}"
remote_url="\${2:-}"

# Appends --remote-url only when git actually gave us one. An explicit
# if/else rather than an array: bash 3.2 (macOS's stock /bin/bash) treats
# "\${arr[@]}" on an EMPTY array as an unbound variable under \`set -u\`, so the
# obvious array form would abort the hook on every push that has no \$2.
__repo_aegis_check() {
  if [ -n "$remote_url" ]; then
    repo-aegis "$@" --remote-url "$remote_url"
  else
    repo-aegis "$@"
  fi
}

exit_rc=0
stdin_lines=()
while read -r local_ref local_sha remote_ref remote_sha; do
  # Captured verbatim (space-joined) so the chaining exec below can
  # replay these exact lines to the repo's own pre-push hook — stdin
  # can only be read once, and this loop already consumed it.
  stdin_lines+=("$local_ref $local_sha $remote_ref $remote_sha")
  if [ "$local_sha" = "$zero" ]; then
    continue
  fi
  if [ "$remote_sha" = "$zero" ]; then
    if ! __repo_aegis_check check --push-ref "$local_ref" --remote "$remote_name"; then
      echo "repo-aegis: blocked push of new ref $local_ref (remote: $remote_name); reason above" >&2
      exit_rc=1
    fi
  else
    range="\${remote_sha}..\${local_sha}"
    if ! __repo_aegis_check check --range "$range"; then
      echo "repo-aegis: blocked push of range $range (ref: $local_ref); reason above" >&2
      exit_rc=1
    fi
  fi
done

if [ "$exit_rc" -ne 0 ]; then
  # Same rule as pre-commit: a repo-aegis hit blocks the push outright
  # and we never reach the chaining step below — an exit-0 chained
  # pre-push must not be able to mask this.
  exit "$exit_rc"
fi

# Chain to the repo's own pre-push hook, if one exists (see the
# pre-commit script's chaining comment for why this exists since v0.7's
# global-by-default core.hooksPath).
# --git-common-dir (NOT --git-path hooks) is deliberate: --git-path
# hooks resolves the EFFECTIVE path, i.e. honors core.hooksPath — which
# right now is US, so it would always "find" ourselves and the
# same-file guard below would skip chaining forever. --git-common-dir
# gives the repo's real .git dir independent of any core.hooksPath
# override (and is shared across linked worktrees), which is what
# holds a hook a human or other tool installed directly.
git_common_dir="$(git rev-parse --git-common-dir 2>/dev/null || true)"
hooks_dir=""
if [ -n "$git_common_dir" ]; then
  hooks_dir="$git_common_dir/hooks"
fi
if [ -n "$hooks_dir" ]; then
  chained="$hooks_dir/pre-push"
  if [ -x "$chained" ] && ! __repo_aegis_same_file "$chained" "$0"; then
    tmp_stdin="$(mktemp 2>/dev/null || true)"
    if [ -n "$tmp_stdin" ]; then
      printf '%s\\n' "\${stdin_lines[@]}" > "$tmp_stdin"
      exec 3< "$tmp_stdin"
      rm -f "$tmp_stdin"
      exec "$chained" "$@" <&3
    fi
    # mktemp unavailable (very unlikely): fall through to the plain
    # exit below rather than risk exec'ing with unpredictable stdin.
  fi
fi

exit "$exit_rc"
`;

export const HOOK_SCRIPTS: Record<HookName, string> = {
  "pre-commit": PRE_COMMIT_SCRIPT,
  "pre-push": PRE_PUSH_SCRIPT,
};

/**
 * sha256 hex digest of the hook script text for `name`. Compared against
 * the digest of the on-disk file by `hooks-state.ts` to detect a script
 * left over from an older `install hooks` run (the `current` flag) —
 * this is what lets a pre-push logic change (or any future edit to these
 * templates) be detected as "installed, but stale" instead of silently
 * running the old behaviour forever.
 */
export function hookScriptDigest(name: HookName): string {
  return createHash("sha256").update(HOOK_SCRIPTS[name]).digest("hex");
}
